version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data

  back:
    build: ./inklumin-back
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/inklumin
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      ML_SERVICE_URL: http://ml:5123
    depends_on:
      - db
      - ml
    ports:
      - "8080:8080"

  ml:
    build: ./inklumin-ml
    ports:
      - "5123:5123"

  front:
    build:
      context: ./inklumin-front
      args:
        INKLUMIN_API_URL: https://api.inklumin.ru/api
    depends_on:
      - back
    ports:
      - "8081:80"
volumes:
  db-data:

